### ISSUE TITLE
ae3.0 cn1101版本下 hotkey面板按下火神冲会导致acr停止工作

### ISSUE THREAD

**Issue by Dewcat** [LittleNightmare/LittleNightmareACR#1]

**Comment by LittleNightmare** [comment]
虽然可能是因为api有变动导致的，但如果可以的话，能说下什么情况下遇到的吗？这样我可以测试一下，或者可以看看目前的更新有没有解决这个问题，我觉得是解决了

**Comment by Dewcat** [comment]
> 虽然可能是因为api有变动导致的，但如果可以的话，能说下什么情况下遇到的吗？这样我可以测试一下，或者可以看看目前的更新有没有解决这个问题，我觉得是解决了

现在火神冲的确不会导致acr停止工作了。但是hotkey里的火神冲也没法像cn1101之前的版本一样正常地进入施法队列了，即使是火神冲已经好了的时候。只能在没有任何技能正在咏唱的时候使用。具体应用在两个读条之间的时候，就是只有激情连打的时候可能可以放出来。
该情况在木桩稳定复现。

**Comment by LittleNightmare** [comment]
啊？不进入施法队列是这次更的 ，因为我打算让火神冲在亮起来的时候才能进。。但，这个正常不应。。哦，我知道了，你等下吧

edit:大概10h前更新过了，版本号是2.3.3.1

**Comment by Dewcat** [comment]
> 啊？不进入施法队列是这次更的 ，因为我打算让火神冲在亮起来的时候才能进。。但，这个正常不应。。哦，我知道了，你等下吧
> 
> edit:大概10h前更新过了，版本号是2.3.3.1
可以正常使用了，赞美梦魇佬

**Comment by Dewcat** [comment]
> 啊？不进入施法队列是这次更的 ，因为我打算让火神冲在亮起来的时候才能进。。但，这个正常不应。。哦，我知道了，你等下吧
> 
> edit:大概10h前更新过了，版本号是2.3.3.1

可以正常使用了，赞美梦魇佬
